spring.application.name=backend-lab
server.port=8081

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Kafka ??? ?? (docker-compose? ?? ???? ? ??:??? ????)
spring.kafka.bootstrap-servers=localhost:9092

# --- Consumer ?? ---
# ??? ?? ??. ?? ????? ???? ?? ????,
# ??? ??? ?? ???? ?? ????? ? ???
spring.kafka.consumer.group-id=notification-group

# ???? ?? ???? ?, ??? ???? ????? ???(earliest) ?? ??? ???(latest)
spring.kafka.consumer.auto-offset-reset=earliest

# ???? key/value? ?? ???? ????(byte -> ??)??
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# JsonDeserializer? ?? ???? ???? ??????? ?? (????? ?? ??, ????? ??? ?? ??)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ???? ?? ??? ?? ? ????? ?? ???? ???? ??
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.backend_lab.notification.dto.NotificationSignal

# --- Producer ?? ---
# ???? key/value? ?? ???? ???(?? -> byte)??
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Valkey(Redis ???? ??) ?? ??
spring.data.redis.host=localhost
spring.data.redis.port=6379